name = "web"
type = "javascript"

account_id = "your_account_id"
workers_dev = true
compatibility_flags = []

[build]
command = "npm run build"  # если есть сборка

[env.production]
route = "web.shugarfreestudio.workers.dev/*"  # ваш поддомен
zone_id = "your_zone_id"  # можно оставить, если нужно

main = "src/index.js"  # укажите точку входа для вашего проекта (например, "src/index.js")
